<title>Love comparator</title>

<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
<link rel="stylesheet" href="css/normalize.css">
<link rel="stylesheet" href="css/style.css">
<script src="js/jquery.js"></script>
<h1 id="title">Contactez-nous</h1>

<form action="http://www.cs.tut.fi/cgi-bin/run/~jkorpela/echo.cgi" method="post">
  <div>
    <label for="nom">Nom :</label>
    <input type="text" id="nom" name="user_name" class="name">
  </div>

  <div>
    <label for="courriel">Email :</label>
    <input type="email" id="courriel" name="user_email">
  </div>

  <div>
    <label for="message">Message :</label>
    <textarea id="message" name="user_message"></textarea>
  </div>

  <div class="button">
    <button type="submit">Envoyer le message</button>
  </div>
</form>
  <a href="http://localhost/PROJET/index.php" class="home">Retour à l'accueil</a>
