<!DOCTYPE html>
<html lang="fr" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Love comparator</title>
  <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/style.css">
  <script src="js/jquery.js"></script>
</head>
<body>
  <header>
    <h1 id="title">Love Comparator</h1>
    <h2 class="title">Comment choisir le bon site de rencontres ?</h1>
    </header>
    <main>
      <div class="free">
        <h2 class="titlefree">Les sites de rencontres: avantages et inconvénients</h2>
        <p></p>
    </div>
    <div class="notfree">

    </div>
      <h4>Les avantages</h4>
        <p>La sélection naturelle est bien faite, par définition sur ce type de sites il n’y a que des célibataires. Du coup, nous en arrivons fatalement au premier avantage : vous n’avez jamais vu autant de célibataires réunies au même endroit et ça, c’est un sacré coup de pouce pour séduire. La plupart des sites de rencontre ne sont pas très chers, certains sont même gratuits. La drague est alors bien moins onéreuse qu’une soirée classique en boîte de nuit.</p>
        <p>La plupart des sites sont assez exhaustifs dans les questions qu’ils vous posent pour compléter votre profil. Du coup, les membres se décrivent avec minutie. Vous allez pouvoir en apprendre beaucoup sur la personnalité, les passions, les rêves et les objectifs de votre futur date. Intrinsèquement, les personnes qui sont sur les sites de rencontre savent pourquoi elles sont là, les femmes veulent vous connaître, sachez en profiter. Vous allez pouvoir goûter au plaisir de la drague par écrit, c’est assez pur quand on y pense, proche des amours épistolaires de l’ancienne bourgeoisie.</p>
        <h4>Les inconvénients</h4>
        <p>Toutes les personnes ne sont pas honnête sur Internet, vous pouvez rencontrer des nanas bizarres voire nocives. Les gens ne s’expriment pas de la même manière à l’oral qu’à l’écrit, la différence entre la personne que vous pensez connaître et celle que vous allez voir en rendez-vous peut parfois vous faire tomber de haut. Attention aux photos, au bout de 3-4 on commence à se faire une idée du physique réel de la personne avec qui on parle.</p>
    <div class="text">
      <h2>Dans les deux cas :</h2>
      <p>La naissance des sites de rencontres a complètement changé les rapports entre homme et femme. D’après certains points de vue, les rencontres sont désormais automatisées et les sentiments ne comptent guère. L’existence des sites pour hommes et femmes mariés tend à confirmer cette théorie. Mais si on analyse bien la situation, la séduction sur le net est un moyen comme un autre de trouver son âme sœur.</p>

        <p>Par ailleurs, les démarches sont toujours les mêmes. Que ce soit dans le monde virtuel ou réel, c’est encore aux hommes de faire le premier pas et la plupart se montrent maladroits. Les femmes, quant à elles, restent toujours mystérieuses. Au bout de plusieurs heures de discussion en ligne, la chance que les relations aboutissent n’est pas garantie. En dépit de tout cela, une chose est sûre : la rencontre sur internet présente beaucoup d’avantages aussi bien pour les hommes que les femmes.</p>



      <h3 id="advice">Lisez nos conseils afin de ne pas vous tromper, connectez-vous ci-dessous ou créez votre compte gratuitement</h3>
      <a class="cta" href="#">Inscrivez-vous ou connectez-vous</a>
    </div>
  </main>
  <footer>
    <nav>
      <ul id="footer">
        <li><a href="http://localhost/PROJET/contact.phtml" class="link">Contactez-nous</a></li>
        <li><a href="http://localhost/PROJET/about.phtml" class="link">Qui sommes-nous</a></li>
        <li><a href="http://localhost/PROJET/legal.phtml" class="link">Mentions légales</a></li>
        <li><a href="#" class="link">Avis</a></li>
      </ul>
    </nav>
    <h3 class="footer">Copyright © 2018-2019 || chevaliermarc.com</h3>

  </footer>

</body>
</html>
