<title>Love comparator</title>
<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
<link rel="stylesheet" href="css/normalize.css">
<link rel="stylesheet" href="css/style.css">
<script src="js/jquery.js"></script>

<h1 id="title">Mentions légales</h1>

<p>Les avis de LOVE COMPARATOR, ne reflètent pas la réalité ou les opinions du créateur du site ou des personnes annexes.</p>
<p>Ce site est un projet privé destiné à ne rien commercialiser, et ne reflète en aucun cas d'opinion quelles qu'elles soient.</p>
<p>Les noms, les marques et les sites nommés ne le sont que dans un but scolaire, les comparatifs ainsi que LOVE COMPARATOR ne reflètent pas la réalité.</p>
<p>La base de données ne peut être vendue, louée et ne sera pas conservée, vu que ce site est destiné à être présenté devant un jury, en vu d'une note d'examen. Une fois ce dernier terminé, la base de donnée sera totalement détruite. Le site restera en ligne pour servir de portfolio uniquement et ne sera en aucun cas représentatif des marques citées, des avis notifiés et des notes attribuées.</p>
<a href="http://localhost/PROJET/index.php" class="home">Retour à l'accueil</a>
